pip install speedtest-cli

C:\Users\Atindra Shekhar>speedtest-cli
# Retrieving speedtest.net configuration...
# Testing from TechX (8.0.3.8)...
# Retrieving speedtest.net server list...
# Selecting best server based on ping...
# Hosted by  [2.42 km]: 13.594 ms
# Testing download speed................................................................................
# Download: 17.39 Mbit/s
# Testing upload speed......................................................................................................
# Upload: 16.48 Mbit/s

C:\Users\Atindra Shekhar>speedtest-cli --share
# Retrieving speedtest.net configuration...
# Testing from TechX (8.0.3.8)...
# Retrieving speedtest.net server list...
# Selecting best server based on ping...
# Hosted by TechX California -WiFi (California) [2.42 km]: 5.589 ms
# Testing download speed................................................................................
# Download: 18.20 Mbit/s
# Testing upload speed......................................................................................................
# Upload: 16.59 Mbit/s
# Share results: http://www.speedtest.net/result/333234953.png

C:\Users\Atindra Shekhar>speedtest-cli --simple
# Ping: 5.632 ms
# Download: 18.56 Mbit/s
# Upload: 16.88 Mbit/s

